name: jagbdot
title: gentleinsight
email: fugitloop@gmail.com
description: Graphic design, ux/ui design, Illustration. # this means to ignore newlines until "baseurl:"
url: "https://gentleinsight.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username: jagbdot
facebook: Juan Antonio GB
linkedin: Juan Antonio Godoy Berner
telephone: +31615047776

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compressed